# FROM golang:alpine as builder

# WORKDIR /app
# COPY . .
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o hellogopher -ldflags="-w -s"

# ENTRYPOINT [ "./hellogopher" ]


FROM golang:1.20 as builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o hellogopher ./...


FROM alpine:3.17 AS production

COPY --from=builder /app .

CMD ["./hellogopher"]